//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanoptoScheduleUploader.Services.SessionManagement {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AuthenticationInfo", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class AuthenticationInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode {
            get {
                return this.AuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthCodeField, value) != true)) {
                    this.AuthCodeField = value;
                    this.RaisePropertyChanged("AuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserKey {
            get {
                return this.UserKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.UserKeyField, value) != true)) {
                    this.UserKeyField = value;
                    this.RaisePropertyChanged("UserKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Note", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class Note : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChannelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Channel {
            get {
                return this.ChannelField;
            }
            set {
                if ((object.ReferenceEquals(this.ChannelField, value) != true)) {
                    this.ChannelField = value;
                    this.RaisePropertyChanged("Channel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SessionID {
            get {
                return this.SessionIDField;
            }
            set {
                if ((this.SessionIDField.Equals(value) != true)) {
                    this.SessionIDField = value;
                    this.RaisePropertyChanged("SessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pagination", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class Pagination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxNumberResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxNumberResults {
            get {
                return this.MaxNumberResultsField;
            }
            set {
                if ((this.MaxNumberResultsField.Equals(value) != true)) {
                    this.MaxNumberResultsField = value;
                    this.RaisePropertyChanged("MaxNumberResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageNumber {
            get {
                return this.PageNumberField;
            }
            set {
                if ((this.PageNumberField.Equals(value) != true)) {
                    this.PageNumberField = value;
                    this.RaisePropertyChanged("PageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListNotesResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListNotesResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.Note[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.Note[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResults {
            get {
                return this.TotalNumberResultsField;
            }
            set {
                if ((this.TotalNumberResultsField.Equals(value) != true)) {
                    this.TotalNumberResultsField = value;
                    this.RaisePropertyChanged("TotalNumberResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Folder", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    [System.SerializableAttribute()]
    public partial class Folder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowPublicNotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowSessionDownloadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AudioPodcastITunesUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AudioRssUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] ChildFoldersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EnablePodcastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPublicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ListUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> ParentFolderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PresentersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] SessionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingsUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoPodcastITunesUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VideoRssUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowPublicNotes {
            get {
                return this.AllowPublicNotesField;
            }
            set {
                if ((this.AllowPublicNotesField.Equals(value) != true)) {
                    this.AllowPublicNotesField = value;
                    this.RaisePropertyChanged("AllowPublicNotes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowSessionDownload {
            get {
                return this.AllowSessionDownloadField;
            }
            set {
                if ((this.AllowSessionDownloadField.Equals(value) != true)) {
                    this.AllowSessionDownloadField = value;
                    this.RaisePropertyChanged("AllowSessionDownload");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AudioPodcastITunesUrl {
            get {
                return this.AudioPodcastITunesUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AudioPodcastITunesUrlField, value) != true)) {
                    this.AudioPodcastITunesUrlField = value;
                    this.RaisePropertyChanged("AudioPodcastITunesUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AudioRssUrl {
            get {
                return this.AudioRssUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.AudioRssUrlField, value) != true)) {
                    this.AudioRssUrlField = value;
                    this.RaisePropertyChanged("AudioRssUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] ChildFolders {
            get {
                return this.ChildFoldersField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildFoldersField, value) != true)) {
                    this.ChildFoldersField = value;
                    this.RaisePropertyChanged("ChildFolders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EnablePodcast {
            get {
                return this.EnablePodcastField;
            }
            set {
                if ((this.EnablePodcastField.Equals(value) != true)) {
                    this.EnablePodcastField = value;
                    this.RaisePropertyChanged("EnablePodcast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPublic {
            get {
                return this.IsPublicField;
            }
            set {
                if ((this.IsPublicField.Equals(value) != true)) {
                    this.IsPublicField = value;
                    this.RaisePropertyChanged("IsPublic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ListUrl {
            get {
                return this.ListUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ListUrlField, value) != true)) {
                    this.ListUrlField = value;
                    this.RaisePropertyChanged("ListUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentFolder {
            get {
                return this.ParentFolderField;
            }
            set {
                if ((this.ParentFolderField.Equals(value) != true)) {
                    this.ParentFolderField = value;
                    this.RaisePropertyChanged("ParentFolder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Presenters {
            get {
                return this.PresentersField;
            }
            set {
                if ((object.ReferenceEquals(this.PresentersField, value) != true)) {
                    this.PresentersField = value;
                    this.RaisePropertyChanged("Presenters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] Sessions {
            get {
                return this.SessionsField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionsField, value) != true)) {
                    this.SessionsField = value;
                    this.RaisePropertyChanged("Sessions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingsUrl {
            get {
                return this.SettingsUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingsUrlField, value) != true)) {
                    this.SettingsUrlField = value;
                    this.RaisePropertyChanged("SettingsUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoPodcastITunesUrl {
            get {
                return this.VideoPodcastITunesUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoPodcastITunesUrlField, value) != true)) {
                    this.VideoPodcastITunesUrlField = value;
                    this.RaisePropertyChanged("VideoPodcastITunesUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VideoRssUrl {
            get {
                return this.VideoRssUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.VideoRssUrlField, value) != true)) {
                    this.VideoRssUrlField = value;
                    this.RaisePropertyChanged("VideoRssUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EditorUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid FolderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FolderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IosVideoUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBroadcastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDownloadableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MP3UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MP4UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputsPageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid[] RemoteRecorderIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SharePageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.SessionState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ThumbUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViewerUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((this.DurationField.Equals(value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EditorUrl {
            get {
                return this.EditorUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.EditorUrlField, value) != true)) {
                    this.EditorUrlField = value;
                    this.RaisePropertyChanged("EditorUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalId {
            get {
                return this.ExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalIdField, value) != true)) {
                    this.ExternalIdField = value;
                    this.RaisePropertyChanged("ExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FolderId {
            get {
                return this.FolderIdField;
            }
            set {
                if ((this.FolderIdField.Equals(value) != true)) {
                    this.FolderIdField = value;
                    this.RaisePropertyChanged("FolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FolderName {
            get {
                return this.FolderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FolderNameField, value) != true)) {
                    this.FolderNameField = value;
                    this.RaisePropertyChanged("FolderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IosVideoUrl {
            get {
                return this.IosVideoUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.IosVideoUrlField, value) != true)) {
                    this.IosVideoUrlField = value;
                    this.RaisePropertyChanged("IosVideoUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBroadcast {
            get {
                return this.IsBroadcastField;
            }
            set {
                if ((this.IsBroadcastField.Equals(value) != true)) {
                    this.IsBroadcastField = value;
                    this.RaisePropertyChanged("IsBroadcast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDownloadable {
            get {
                return this.IsDownloadableField;
            }
            set {
                if ((this.IsDownloadableField.Equals(value) != true)) {
                    this.IsDownloadableField = value;
                    this.RaisePropertyChanged("IsDownloadable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MP3Url {
            get {
                return this.MP3UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MP3UrlField, value) != true)) {
                    this.MP3UrlField = value;
                    this.RaisePropertyChanged("MP3Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MP4Url {
            get {
                return this.MP4UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MP4UrlField, value) != true)) {
                    this.MP4UrlField = value;
                    this.RaisePropertyChanged("MP4Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotesURL {
            get {
                return this.NotesURLField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesURLField, value) != true)) {
                    this.NotesURLField = value;
                    this.RaisePropertyChanged("NotesURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputsPageUrl {
            get {
                return this.OutputsPageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputsPageUrlField, value) != true)) {
                    this.OutputsPageUrlField = value;
                    this.RaisePropertyChanged("OutputsPageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] RemoteRecorderIds {
            get {
                return this.RemoteRecorderIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.RemoteRecorderIdsField, value) != true)) {
                    this.RemoteRecorderIdsField = value;
                    this.RaisePropertyChanged("RemoteRecorderIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SharePageUrl {
            get {
                return this.SharePageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SharePageUrlField, value) != true)) {
                    this.SharePageUrlField = value;
                    this.RaisePropertyChanged("SharePageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.StartTimeField;
            }
            set {
                if ((this.StartTimeField.Equals(value) != true)) {
                    this.StartTimeField = value;
                    this.RaisePropertyChanged("StartTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.SessionState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusMessage {
            get {
                return this.StatusMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusMessageField, value) != true)) {
                    this.StatusMessageField = value;
                    this.RaisePropertyChanged("StatusMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ThumbUrl {
            get {
                return this.ThumbUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ThumbUrlField, value) != true)) {
                    this.ThumbUrlField = value;
                    this.RaisePropertyChanged("ThumbUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViewerUrl {
            get {
                return this.ViewerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ViewerUrlField, value) != true)) {
                    this.ViewerUrlField = value;
                    this.RaisePropertyChanged("ViewerUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionState", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum SessionState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scheduled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recording = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Broadcasting = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Processing = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Complete = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListSessionsRequest", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListSessionsRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FolderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.Pagination PaginationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> RemoteRecorderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.SessionSortField SortByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SortIncreasingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.SessionState[] StatesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FolderId {
            get {
                return this.FolderIdField;
            }
            set {
                if ((this.FolderIdField.Equals(value) != true)) {
                    this.FolderIdField = value;
                    this.RaisePropertyChanged("FolderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.Pagination Pagination {
            get {
                return this.PaginationField;
            }
            set {
                if ((object.ReferenceEquals(this.PaginationField, value) != true)) {
                    this.PaginationField = value;
                    this.RaisePropertyChanged("Pagination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> RemoteRecorderId {
            get {
                return this.RemoteRecorderIdField;
            }
            set {
                if ((this.RemoteRecorderIdField.Equals(value) != true)) {
                    this.RemoteRecorderIdField = value;
                    this.RaisePropertyChanged("RemoteRecorderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.SessionSortField SortBy {
            get {
                return this.SortByField;
            }
            set {
                if ((this.SortByField.Equals(value) != true)) {
                    this.SortByField = value;
                    this.RaisePropertyChanged("SortBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortIncreasing {
            get {
                return this.SortIncreasingField;
            }
            set {
                if ((this.SortIncreasingField.Equals(value) != true)) {
                    this.SortIncreasingField = value;
                    this.RaisePropertyChanged("SortIncreasing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.SessionState[] States {
            get {
                return this.StatesField;
            }
            set {
                if ((object.ReferenceEquals(this.StatesField, value) != true)) {
                    this.StatesField = value;
                    this.RaisePropertyChanged("States");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SessionSortField", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum SessionSortField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duration = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        State = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Relevance = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListSessionsResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    [System.SerializableAttribute()]
    public partial class ListSessionsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.Session[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.Session[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResults {
            get {
                return this.TotalNumberResultsField;
            }
            set {
                if ((this.TotalNumberResultsField.Equals(value) != true)) {
                    this.TotalNumberResultsField = value;
                    this.RaisePropertyChanged("TotalNumberResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListFoldersRequest", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class ListFoldersRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.Pagination Pagination { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> ParentFolderId { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PublicOnly { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.FolderSortField SortBy { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SortIncreasing { get; set; }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool WildcardSearchNameOnly { get; set; }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FolderSortField", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    public enum FolderSortField : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Name = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sessions = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Relavance = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListFoldersResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V42.Soa" +
        "p")]
    [System.SerializableAttribute()]
    public partial class ListFoldersResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PanoptoScheduleUploader.Services.SessionManagement.Folder[] ResultsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalNumberResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PanoptoScheduleUploader.Services.SessionManagement.Folder[] Results {
            get {
                return this.ResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultsField, value) != true)) {
                    this.ResultsField = value;
                    this.RaisePropertyChanged("Results");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalNumberResults {
            get {
                return this.TotalNumberResultsField;
            }
            set {
                if ((this.TotalNumberResultsField.Equals(value) != true)) {
                    this.TotalNumberResultsField = value;
                    this.RaisePropertyChanged("TotalNumberResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecorderDownloadUrlResponse", Namespace="http://schemas.datacontract.org/2004/07/Panopto.Server.Services.PublicAPI.V40")]
    [System.SerializableAttribute()]
    public partial class RecorderDownloadUrlResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MacRecorderDownloadUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WindowsRecorderDownloadUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WindowsRemoteRecorderDownloadUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacRecorderDownloadUrl {
            get {
                return this.MacRecorderDownloadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MacRecorderDownloadUrlField, value) != true)) {
                    this.MacRecorderDownloadUrlField = value;
                    this.RaisePropertyChanged("MacRecorderDownloadUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsRecorderDownloadUrl {
            get {
                return this.WindowsRecorderDownloadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WindowsRecorderDownloadUrlField, value) != true)) {
                    this.WindowsRecorderDownloadUrlField = value;
                    this.RaisePropertyChanged("WindowsRecorderDownloadUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsRemoteRecorderDownloadUrl {
            get {
                return this.WindowsRemoteRecorderDownloadUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.WindowsRemoteRecorderDownloadUrlField, value) != true)) {
                    this.WindowsRemoteRecorderDownloadUrlField = value;
                    this.RaisePropertyChanged("WindowsRemoteRecorderDownloadUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SessionManagement.ISessionManagement")]
    public interface ISessionManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/DeleteNote", ReplyAction="http://tempuri.org/ISessionManagement/DeleteNoteResponse")]
        void DeleteNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetNote", ReplyAction="http://tempuri.org/ISessionManagement/GetNoteResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Note GetNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/ListNotes", ReplyAction="http://tempuri.org/ISessionManagement/ListNotesResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.ListNotesResponse ListNotes(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, PanoptoScheduleUploader.Services.SessionManagement.Pagination pagination, System.Nullable<System.Guid> creatorId, string channel, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/AreUsersNotesPublic", ReplyAction="http://tempuri.org/ISessionManagement/AreUsersNotesPublicResponse")]
        bool AreUsersNotesPublic(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid userId, System.Guid sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/SetNotesPublic", ReplyAction="http://tempuri.org/ISessionManagement/SetNotesPublicResponse")]
        void SetNotesPublic(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, bool areNotesPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/IsDropbox", ReplyAction="http://tempuri.org/ISessionManagement/IsDropboxResponse")]
        bool IsDropbox(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/CreateCaptionByRelativeTime", ReplyAction="http://tempuri.org/ISessionManagement/CreateCaptionByRelativeTimeResponse")]
        void CreateCaptionByRelativeTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, double timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/CreateCaptionByAbsoluteTime", ReplyAction="http://tempuri.org/ISessionManagement/CreateCaptionByAbsoluteTimeResponse")]
        void CreateCaptionByAbsoluteTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UploadTranscript", ReplyAction="http://tempuri.org/ISessionManagement/UploadTranscriptResponse")]
        void UploadTranscript(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string file);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/AddFolder", ReplyAction="http://tempuri.org/ISessionManagement/AddFolderResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Folder AddFolder(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, System.Nullable<System.Guid> parentFolder, bool isPublic);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/AddSession", ReplyAction="http://tempuri.org/ISessionManagement/AddSessionResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Session AddSession(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetFoldersById", ReplyAction="http://tempuri.org/ISessionManagement/GetFoldersByIdResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Folder[] GetFoldersById(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] folderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetFoldersByExternalId", ReplyAction="http://tempuri.org/ISessionManagement/GetFoldersByExternalIdResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Folder[] GetFoldersByExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string[] folderExternalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetSessionsById", ReplyAction="http://tempuri.org/ISessionManagement/GetSessionsByIdResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Session[] GetSessionsById(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetSessionsByExternalId", ReplyAction="http://tempuri.org/ISessionManagement/GetSessionsByExternalIdResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Session[] GetSessionsByExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string[] sessionExternalIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetSessionsList", ReplyAction="http://tempuri.org/ISessionManagement/GetSessionsListResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.ListSessionsResponse GetSessionsList(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, PanoptoScheduleUploader.Services.SessionManagement.ListSessionsRequest request, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetFoldersList", ReplyAction="http://tempuri.org/ISessionManagement/GetFoldersListResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.ListFoldersResponse GetFoldersList(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, PanoptoScheduleUploader.Services.SessionManagement.ListFoldersRequest request, string searchQuery);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateSessionName", ReplyAction="http://tempuri.org/ISessionManagement/UpdateSessionNameResponse")]
        void UpdateSessionName(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateSessionDescription", ReplyAction="http://tempuri.org/ISessionManagement/UpdateSessionDescriptionResponse")]
        void UpdateSessionDescription(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateSessionIsBroadcast", ReplyAction="http://tempuri.org/ISessionManagement/UpdateSessionIsBroadcastResponse")]
        void UpdateSessionIsBroadcast(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, bool isBroadcast);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/MoveSessions", ReplyAction="http://tempuri.org/ISessionManagement/MoveSessionsResponse")]
        void MoveSessions(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds, System.Guid folderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateSessionExternalId", ReplyAction="http://tempuri.org/ISessionManagement/UpdateSessionExternalIdResponse")]
        void UpdateSessionExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderName", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderNameResponse")]
        void UpdateFolderName(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderDescription", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderDescriptionResponse")]
        void UpdateFolderDescription(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderEnablePodcast", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderEnablePodcastResponse")]
        void UpdateFolderEnablePodcast(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool enablePodcast);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderAllowPublicNotes", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderAllowPublicNotesResponse")]
        void UpdateFolderAllowPublicNotes(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool allowPublicNotes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderAllowSessionDownload", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderAllowSessionDownloadResponse")]
        void UpdateFolderAllowSessionDownload(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool allowSessionDownload);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderParent", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderParentResponse")]
        void UpdateFolderParent(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, System.Nullable<System.Guid> parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/UpdateFolderExternalId", ReplyAction="http://tempuri.org/ISessionManagement/UpdateFolderExternalIdResponse")]
        void UpdateFolderExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/DeleteSessions", ReplyAction="http://tempuri.org/ISessionManagement/DeleteSessionsResponse")]
        void DeleteSessions(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/DeleteFolders", ReplyAction="http://tempuri.org/ISessionManagement/DeleteFoldersResponse")]
        void DeleteFolders(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] folderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/ProvisionExternalCourse", ReplyAction="http://tempuri.org/ISessionManagement/ProvisionExternalCourseResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Folder ProvisionExternalCourse(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, string externalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/SetExternalCourseAccess", ReplyAction="http://tempuri.org/ISessionManagement/SetExternalCourseAccessResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.Folder[] SetExternalCourseAccess(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, string externalId, System.Guid[] folderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/GetRecorderDownloadUrls", ReplyAction="http://tempuri.org/ISessionManagement/GetRecorderDownloadUrlsResponse")]
        PanoptoScheduleUploader.Services.SessionManagement.RecorderDownloadUrlResponse GetRecorderDownloadUrls();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/CreateNoteByRelativeTime", ReplyAction="http://tempuri.org/ISessionManagement/CreateNoteByRelativeTimeResponse")]
        System.Guid CreateNoteByRelativeTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, string channel, double timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/CreateNoteByAbsoluteTime", ReplyAction="http://tempuri.org/ISessionManagement/CreateNoteByAbsoluteTimeResponse")]
        System.Guid CreateNoteByAbsoluteTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, string channel, System.DateTime timestamp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISessionManagement/EditNote", ReplyAction="http://tempuri.org/ISessionManagement/EditNoteResponse")]
        void EditNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId, string newText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISessionManagementChannel : PanoptoScheduleUploader.Services.SessionManagement.ISessionManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SessionManagementClient : System.ServiceModel.ClientBase<PanoptoScheduleUploader.Services.SessionManagement.ISessionManagement>, PanoptoScheduleUploader.Services.SessionManagement.ISessionManagement {
        
        public SessionManagementClient() {
        }
        
        public SessionManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId) {
            base.Channel.DeleteNote(auth, noteId, sessionId);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Note GetNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId) {
            return base.Channel.GetNote(auth, noteId, sessionId);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.ListNotesResponse ListNotes(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, PanoptoScheduleUploader.Services.SessionManagement.Pagination pagination, System.Nullable<System.Guid> creatorId, string channel, string searchQuery) {
            return base.Channel.ListNotes(auth, sessionId, pagination, creatorId, channel, searchQuery);
        }
        
        public bool AreUsersNotesPublic(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid userId, System.Guid sessionId) {
            return base.Channel.AreUsersNotesPublic(auth, userId, sessionId);
        }
        
        public void SetNotesPublic(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, bool areNotesPublic) {
            base.Channel.SetNotesPublic(auth, sessionId, areNotesPublic);
        }
        
        public bool IsDropbox(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId) {
            return base.Channel.IsDropbox(auth, folderId);
        }
        
        public void CreateCaptionByRelativeTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, double timestamp) {
            base.Channel.CreateCaptionByRelativeTime(auth, sessionId, text, timestamp);
        }
        
        public void CreateCaptionByAbsoluteTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, System.DateTime timestamp) {
            base.Channel.CreateCaptionByAbsoluteTime(auth, sessionId, text, timestamp);
        }
        
        public void UploadTranscript(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string file) {
            base.Channel.UploadTranscript(auth, sessionId, file);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Folder AddFolder(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, System.Nullable<System.Guid> parentFolder, bool isPublic) {
            return base.Channel.AddFolder(auth, name, parentFolder, isPublic);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Session AddSession(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, System.Guid folderId, bool isBroadcast) {
            return base.Channel.AddSession(auth, name, folderId, isBroadcast);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Folder[] GetFoldersById(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] folderIds) {
            return base.Channel.GetFoldersById(auth, folderIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Folder[] GetFoldersByExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string[] folderExternalIds) {
            return base.Channel.GetFoldersByExternalId(auth, folderExternalIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Session[] GetSessionsById(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds) {
            return base.Channel.GetSessionsById(auth, sessionIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Session[] GetSessionsByExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string[] sessionExternalIds) {
            return base.Channel.GetSessionsByExternalId(auth, sessionExternalIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.ListSessionsResponse GetSessionsList(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, PanoptoScheduleUploader.Services.SessionManagement.ListSessionsRequest request, string searchQuery) {
            return base.Channel.GetSessionsList(auth, request, searchQuery);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.ListFoldersResponse GetFoldersList(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, PanoptoScheduleUploader.Services.SessionManagement.ListFoldersRequest request, string searchQuery) {
            return base.Channel.GetFoldersList(auth, request, searchQuery);
        }
        
        public void UpdateSessionName(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string name) {
            base.Channel.UpdateSessionName(auth, sessionId, name);
        }
        
        public void UpdateSessionDescription(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string description) {
            base.Channel.UpdateSessionDescription(auth, sessionId, description);
        }
        
        public void UpdateSessionIsBroadcast(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, bool isBroadcast) {
            base.Channel.UpdateSessionIsBroadcast(auth, sessionId, isBroadcast);
        }
        
        public void MoveSessions(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds, System.Guid folderId) {
            base.Channel.MoveSessions(auth, sessionIds, folderId);
        }
        
        public void UpdateSessionExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string externalId) {
            base.Channel.UpdateSessionExternalId(auth, sessionId, externalId);
        }
        
        public void UpdateFolderName(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string name) {
            base.Channel.UpdateFolderName(auth, folderId, name);
        }
        
        public void UpdateFolderDescription(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string description) {
            base.Channel.UpdateFolderDescription(auth, folderId, description);
        }
        
        public void UpdateFolderEnablePodcast(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool enablePodcast) {
            base.Channel.UpdateFolderEnablePodcast(auth, folderId, enablePodcast);
        }
        
        public void UpdateFolderAllowPublicNotes(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool allowPublicNotes) {
            base.Channel.UpdateFolderAllowPublicNotes(auth, folderId, allowPublicNotes);
        }
        
        public void UpdateFolderAllowSessionDownload(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, bool allowSessionDownload) {
            base.Channel.UpdateFolderAllowSessionDownload(auth, folderId, allowSessionDownload);
        }
        
        public void UpdateFolderParent(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, System.Nullable<System.Guid> parentId) {
            base.Channel.UpdateFolderParent(auth, folderId, parentId);
        }
        
        public void UpdateFolderExternalId(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid folderId, string externalId) {
            base.Channel.UpdateFolderExternalId(auth, folderId, externalId);
        }
        
        public void DeleteSessions(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] sessionIds) {
            base.Channel.DeleteSessions(auth, sessionIds);
        }
        
        public void DeleteFolders(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid[] folderIds) {
            base.Channel.DeleteFolders(auth, folderIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Folder ProvisionExternalCourse(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, string externalId) {
            return base.Channel.ProvisionExternalCourse(auth, name, externalId);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.Folder[] SetExternalCourseAccess(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, string name, string externalId, System.Guid[] folderIds) {
            return base.Channel.SetExternalCourseAccess(auth, name, externalId, folderIds);
        }
        
        public PanoptoScheduleUploader.Services.SessionManagement.RecorderDownloadUrlResponse GetRecorderDownloadUrls() {
            return base.Channel.GetRecorderDownloadUrls();
        }
        
        public System.Guid CreateNoteByRelativeTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, string channel, double timestamp) {
            return base.Channel.CreateNoteByRelativeTime(auth, sessionId, text, channel, timestamp);
        }
        
        public System.Guid CreateNoteByAbsoluteTime(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid sessionId, string text, string channel, System.DateTime timestamp) {
            return base.Channel.CreateNoteByAbsoluteTime(auth, sessionId, text, channel, timestamp);
        }
        
        public void EditNote(PanoptoScheduleUploader.Services.SessionManagement.AuthenticationInfo auth, System.Guid noteId, System.Guid sessionId, string newText) {
            base.Channel.EditNote(auth, noteId, sessionId, newText);
        }
    }
}
